version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/aashu
      - SECRET_KEY=${SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - OPENAI_LOG=info
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=aashu
    ports:
      - "5432:5432"

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm run dev -- -H 0.0.0.0"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://192.168.1.38:8000
    depends_on:
      - api

volumes:
  postgres_data:

