version: '3'

services:
  api:
    restart: always
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      - NODE_ENV=production
    
  frontend:
    command: bash -c "npm install && npm run build && npm run start"
    restart: always
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api:8000 